include:
  - project: arc-one/infrastructure/gitlab-ci
    ref: main
    file: pipeline_biopro_domain.gitlab-ci.yml
  - project: arc-one/infrastructure/gitlab-ci
    ref: main
    file: spec.build_ui.pipeline.yml
    inputs:
      service: distribution-ui
  - project: arc-one/infrastructure/gitlab-ci
    ref: main
    file: spec.backend.pipeline.yml
    inputs:
      service: shipping
  - project: arc-one/infrastructure/gitlab-ci
    ref: main
    file: spec.backend.pipeline.yml
    inputs:
      service: order
  - project: arc-one/infrastructure/gitlab-ci
    ref: main
    file: spec.backend.pipeline.yml
    inputs:
      service: partnerorderprovider
