{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "api.fullname" . }}-vs
  namespace: istio-system
spec:
  hosts:
    - {{ .Values.domain }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        {{- toYaml .Values.istio.services | nindent 8 }}
      corsPolicy:
        allowCredentials: true
        allowHeaders:
          - Content-Type
          - Authorization
          - Accept
          - x-rsa-time-zone
        allowMethods:
          - POST
          - GET
          - PUT
          - DELETE
        allowOrigins:
          - exact: '*'
        exposeHeaders:
          - X-Total-Count
        maxAge: 24h
      route:
        - destination:
            host: {{ include "api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end }}
